<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Muebleria HR</title>
  <?php Tag::css('vendors/bootstrap/dist/css/bootstrap.min') ?>
  <?php Tag::css('vendors/font-awesome/css/font-awesome.min') ?>
  <?php Tag::css('vendors/nprogress/nprogress') ?>
  <?php Tag::css('custom.min') ?>
  <?php Tag::css('vendors/font-awesome/css/font-awesome.min') ?>
  <?php Tag::css('vendors/animate.css/animate.min') ?>
  <?php Tag::css('vendors/fullcalendar/dist/fullcalendar.min') ?>
  <?php Tag::css('vendors/fullcalendar/dist/fullcalendar.print') ?>
  <?php Tag::css('build/css/custom')?>

  <?php echo Html::includeCss() ?>
</head>
<body>
  <?php View::content(); ?>
  <?php echo Tag::js('vendors/jquery/dist/jquery.min');?>
  <?php echo Tag::js('vendors/bootstrap/dist/js/bootstrap.min');?>
  <?php echo Tag::js('vendors/fastclick/lib/fastclick');?>
  <?php echo Tag::js('vendors/nprogress/nprogress');?>
  <?php echo Tag::js('vendors/moment/min/moment.min');?>
  <?php echo Tag::js('vendors/fullcalendar/dist/fullcalendar.min');?>
  <?php echo Tag::js('js/custom.min');?>
</body>
</html>

